(function(){
 const policyKey='bombhr-attendance-deduction-policy',eventKey='bombhr-demo-events',adjustmentKey='bombhr-payroll-adjustments-v123';
 const defaults={scheduledStart:'08:45',graceMinutes:1,perMinuteDeduction:100,singleDeductionCap:1500,monthlyMinuteThreshold:30,monthlyCountThreshold:3,severeLateMinutes:180,severeCountThreshold:2,severeObservationMonths:3,missingPunchDeadlineDays:3,missingPunchDeductionType:'daily-wage',dailyWageDivisor:30};
 const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch(e){return fallback}};
 const policy=()=>({...defaults,...read(policyKey,{})});
 const events=()=>read(eventKey,[]);
 function minutesOf(time){const [h,m]=time.split(':').map(Number);return h*60+m}
 function monthKey(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`}
 function saveEvent(event){const list=events();list.unshift({...event,eventId:event.id||`AT${Date.now()}`,createdAt:new Date().toISOString()});localStorage.setItem(eventKey,JSON.stringify(list.slice(0,200)));try{new BroadcastChannel('bombhr-demo').postMessage({key:eventKey,time:Date.now()})}catch(e){}}
 function addPayrollDeduction(employeeId,name,amount,note,eventId){const all=read(adjustmentKey,{}),items=all[employeeId]||(all[employeeId]=[]);if(items.some(item=>item.eventId===eventId))return;items.push({name,type:'扣款',amount,note,usage:'依出勤事件自動產生',operator:'出勤規則引擎',time:new Date().toLocaleString('zh-TW',{hour12:false}),eventId});localStorage.setItem(adjustmentKey,JSON.stringify(all))}
 function calculateLate(displayTime){const p=policy(),late=Math.max(0,minutesOf(displayTime)-minutesOf(p.scheduledStart));return {late,deduction:late>p.graceMinutes?Math.min(late*p.perMinuteDeduction,p.singleDeductionCap):0,policy:p}}
 function recordClockIn(displayTime,method){const employeeId='AB00008',employee='佑',{late,deduction,policy:p}=calculateLate(displayTime),id=`LATE-${Date.now()}`,month=monthKey(),recent=events().filter(e=>e.category==='attendance'&&e.action==='late'&&e.employeeId===employeeId),monthly=recent.filter(e=>e.month===month),severeRecent=recent.filter(e=>e.lateMinutes>=p.severeLateMinutes&&Date.now()-new Date(e.createdAt).getTime()<=p.severeObservationMonths*31*864e5),monthlyMinutes=monthly.reduce((sum,e)=>sum+Number(e.lateMinutes||0),0)+late,monthlyCount=monthly.length+(late>0?1:0),severeCount=severeRecent.length+(late>=p.severeLateMinutes?1:0);if(late<=p.graceMinutes)return {late:0,deduction:0,status:'正常'};saveEvent({id,category:'attendance',action:'late',employee,employeeId,month,scheduledTime:p.scheduledStart,actualTime:displayTime,lateMinutes:late,deduction,status:'遲到',monthlyMinutes,monthlyCount,policySnapshot:p,method});if(deduction>0)addPayrollDeduction(employeeId,'遲到扣款',deduction,`${month}・應到 ${p.scheduledStart}／打卡 ${displayTime}／遲到 ${late} 分鐘`,id);if(monthlyMinutes>p.monthlyMinuteThreshold||monthlyCount>p.monthlyCountThreshold)saveEvent({id:`THRESHOLD-${Date.now()}`,category:'attendance',action:'monthly-threshold',employee,employeeId,status:'超過企業遲到門檻',monthlyMinutes,monthlyCount,requiresReview:true});if(severeCount>=p.severeCountThreshold)saveEvent({id:`SEVERE-${Date.now()}`,category:'approval',subtype:'attendance-review',title:'重大遲到／革職條件審查',employee,employeeId,period:`近 ${p.severeObservationMonths} 個月`,duration:`第 ${severeCount} 次達 ${p.severeLateMinutes} 分鐘以上`,reason:'系統僅建立人事審查，不會自動革職',status:'review',statusText:'等待人事審查',submitted:new Date().toLocaleString('zh-TW',{hour12:false})});return {late,deduction,status:`遲到 ${late} 分鐘・扣款 NT$ ${deduction.toLocaleString()}`}}
 window.bombhrRecordMissingPunch=function(shiftDate,baseSalary=30300){const p=policy(),id=`MISS-${Date.now()}`,daily=Math.round(baseSalary/p.dailyWageDivisor);saveEvent({id,category:'approval',subtype:'correction',title:'忘記打卡補簽',employee:'王小明',employeeId:'AB00128',period:shiftDate,duration:`${p.missingPunchDeadlineDays} 個工作日內補簽`,reason:'逾期未補簽將依企業設定扣除一日薪',status:'review',statusText:'等待主管補簽',submitted:new Date().toLocaleString('zh-TW',{hour12:false}),deadlineWorkdays:p.missingPunchDeadlineDays,expiryDeduction:daily,policySnapshot:p});return id};
 window.bombhrExpireMissingPunch=function(id){const event=events().find(e=>e.id===id);if(!event||event.status!=='review')return false;addPayrollDeduction(event.employeeId,'逾期未補卡扣款',event.expiryDeduction,`${event.period} 忘記打卡，超過 ${event.deadlineWorkdays} 個工作日未完成補簽`,id);event.status='expired';event.statusText='逾期未補簽・已扣一日薪';localStorage.setItem(eventKey,JSON.stringify(events()));return true};
 const originalPunch=window.punch;window.punch=function(){if(window.punchState===0||typeof punchState!=='undefined'&&punchState===0){const time=nowTime().slice(0,5),result=recordClockIn(time,window.activeMethod||'APP');originalPunch();if(result.late>0)toast(`${result.status}，已寫入本月薪資扣款`)}else originalPunch()};
 window.bombhrAttendancePolicyDefaults=defaults;window.bombhrCalculateLate=calculateLate;
})();
