(function(){
 const person=window.BOMBHR_APP_EMPLOYEE||{employeeId:'AB00008',name:'佑',position:'前端工程師'},documentKey='bombhr-health-documents-v148',employeeId=person.employeeId,employeeName=person.name,position=person.position;
 const config=()=>window.BOMBHR_CERTIFICATE_REQUIREMENTS?.forPosition(position)||{required:['健康檢查／體檢證明'],recommended:[]};
 const read=()=>{try{return JSON.parse(localStorage.getItem(documentKey)||'[]')}catch(e){return []}};
 const save=value=>localStorage.setItem(documentKey,JSON.stringify(value));
 const status=doc=>doc.reviewStatus==='有效'?'人事已確認':doc.reviewStatus==='退回補件'?'退回補件':'等待人事確認';
 function render(){const view=document.getElementById('certificateSubview');if(!view)return;const rule=config(),docs=read().filter(doc=>doc.employeeId===employeeId),items=[...new Set([...rule.required,...rule.recommended])];view.innerHTML=`<div class="subview-head"><button class="back-btn" id="closeCertificateSubview">‹</button><h2>我的證照與文件</h2></div><div class="certificate-app-banner"><b>${employeeName}・${position}</b><small>由公司依職位指派；上傳後交由財務／人事確認。</small></div><div class="certificate-app-list">${items.map(type=>{const doc=docs.find(item=>item.type===type),uploaded=!!doc?.attachmentData,required=rule.required.includes(type);return `<div class="certificate-app-card"><div><b>${type}</b><small>${required?'必備文件':'建議補充・不影響缺件狀態'}</small></div><span class="certificate-state ${uploaded?'uploaded':''}">${uploaded?status(doc):required?'待補上傳':'尚未上傳'}</span><button data-app-certificate="${type}">${uploaded?'重新上傳':'上傳文件'}</button></div>`}).join('')}</div><div class="certificate-app-note">員工可從APP上傳掃描檔或照片；紙本正本位置及最終有效狀態由人事後台維護。</div>`;document.getElementById('closeCertificateSubview').onclick=()=>closeSubview('certificateSubview');view.querySelectorAll('[data-app-certificate]').forEach(button=>button.onclick=()=>uploadForm(button.dataset.appCertificate))}
 function uploadForm(type){let root=document.getElementById('certificateUploadSheet');if(!root){root=document.createElement('div');root.id='certificateUploadSheet';root.className='certificate-upload-sheet';document.body.append(root)}root.innerHTML=`<div><h3>${type}</h3><p>${employeeName}・${employeeId}・上傳後等待人事確認</p><label>檢查／發證日期<input id="appCertificateDate" type="date"></label><label>有效期限（沒有可留空）<input id="appCertificateExpiry" type="date"></label><label>檢查／發證機構<input id="appCertificateInstitution" placeholder="請輸入機構名稱"></label><label>證明文件<input id="appCertificateFile" type="file" accept="application/pdf,image/jpeg,image/png,image/webp"></label><small id="appCertificateError"></small><div class="certificate-sheet-actions"><button id="cancelCertificateUpload">取消</button><button id="saveCertificateUpload">送交人事審核</button></div></div>`;root.classList.add('show');document.getElementById('cancelCertificateUpload').onclick=()=>root.classList.remove('show');document.getElementById('saveCertificateUpload').onclick=()=>{const date=document.getElementById('appCertificateDate').value,file=document.getElementById('appCertificateFile').files[0],error=document.getElementById('appCertificateError');if(!date||!file){error.textContent='請填寫日期並選擇證明文件';return}if(file.size>1258291){error.textContent='檔案不可超過 1.2 MB';return}const reader=new FileReader();reader.onload=()=>{const all=read(),existing=all.findIndex(doc=>doc.employeeId===employeeId&&doc.type===type),record={id:existing>=0?all[existing].id:`HD-${Date.now()}`,employeeId,type,institution:document.getElementById('appCertificateInstitution').value.trim(),examDate:date,expiryDate:document.getElementById('appCertificateExpiry').value,documentNumber:'',paperLocation:'',reviewStatus:'待確認',employeeCanView:true,notes:'Employee App 本人上傳，等待人事確認',attachmentData:reader.result,attachmentName:file.name,uploadedBy:`${employeeName}・${employeeId}`,uploadSource:'Employee App',updatedAt:new Date().toISOString()};if(existing>=0)all[existing]=record;else all.unshift(record);save(all);const events=(()=>{try{return JSON.parse(localStorage.getItem('bombhr-demo-events')||'[]')}catch(e){return []}})();events.unshift({category:'hr-task',subtype:'certificate-review',id:`CERT-${record.id}`,title:'待審核員工證照／文件',employee:employeeName,employeeId,type,status:'pending',statusText:'等待財務／人事確認',createdAt:record.updatedAt});localStorage.setItem('bombhr-demo-events',JSON.stringify(events.slice(0,100)));root.classList.remove('show');render();toast('文件已上傳，等待財務／人事確認')};reader.readAsDataURL(file)}}
 function setup(){const menu=document.querySelector('#myView .menu-list');if(menu&&!document.getElementById('employeeCertificateEntry'))menu.insertAdjacentHTML('afterbegin','<button class="menu-row" id="employeeCertificateEntry" style="width:100%;border:0;background:none;color:inherit;text-align:left"><span class="certificate-menu-icon">證</span><b>我的證照與文件</b><span>›</span></button>');document.getElementById('employeeCertificateEntry')?.addEventListener('click',()=>{openSubview('certificateSubview');render()});if(!document.getElementById('certificateSubview'))document.body.insertAdjacentHTML('beforeend','<section class="subview" id="certificateSubview"></section>');render()}
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',setup):setup();window.addEventListener('storage',event=>{if(event.key===documentKey||event.key===window.BOMBHR_CERTIFICATE_REQUIREMENTS?.key)render()});
})();
