(function(){
 const eventKey='bombhr-demo-events',recordKey='bombhr-emergency-leave-records';
 const supervisor=(()=>{const base={name:'OG',employeeId:'AB00118',role:'當班主管',department:'營運－企劃部',shift:'08:45–18:00',companyPhone:'04-2258-1688',privatePhone:'0912-345-678',line:'ABOMB OG',lineId:'abomb.supervisor',lineUrl:'https://line.me/ti/p/l__q4CyUgN',lineQr:'',allowEmployeeView:true,verified:true,delegate:''};try{return {...base,...JSON.parse(localStorage.getItem('bombhr-supervisor-contact-master')||'{}')}}catch(e){return base}})();
 let contactedBy='',contactStartedAt='';
 const now=()=>new Date().toLocaleString('zh-TW',{hour12:false});
 const read=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch(e){return fallback}};
 const write=(key,value)=>{localStorage.setItem(key,JSON.stringify(value));window.dispatchEvent(new CustomEvent('bombhr-demo-update'));try{new BroadcastChannel('bombhr-demo').postMessage({key,time:Date.now()})}catch(e){}};
 function openEmergencyLeave(){document.getElementById('emergencyLeaveSubview')?.classList.add('active');renderRecords()}
 function closeEmergencyLeave(){document.getElementById('emergencyLeaveSubview')?.classList.remove('active')}
 function markContact(method){contactedBy=method;contactStartedAt=now();const status=document.getElementById('emergencyContactStatus'),confirm=document.getElementById('confirmEmergencyContact');if(status)status.textContent=`已於 ${contactStartedAt} 發起${method}，聯絡完成後請按下方按鈕送出紀錄。`;if(confirm)confirm.disabled=false}
 function submitEmergency(){if(!contactedBy)return toast('請先使用電話或 LINE 聯絡當班主管');const type=document.getElementById('emergencyLeaveType').value,reason=document.getElementById('emergencyLeaveReason').value.trim();if(!reason)return toast('請填寫簡短請假原因');const id='EL'+Date.now(),submitted=now(),record={id,type,reason,employee:'王小明',employeeId:'AB00128',supervisor,contactMethod:contactedBy,contactStartedAt,employeeConfirmedAt:submitted,status:'review',statusText:'等待主管確認已接獲聯絡',createdAt:new Date().toISOString()};const records=read(recordKey);records.unshift(record);write(recordKey,records.slice(0,50));const events=read(eventKey);events.unshift({category:'approval',subtype:'leave',emergency:true,id,eventId:id,title:`緊急請假・${type}`,employee:record.employee,employeeId:record.employeeId,period:'今日班別 08:45–18:00',duration:'依實際請假時間',agent:'待主管安排',reason:`${reason}｜員工已透過${contactedBy}聯絡 ${supervisor.name}｜發起 ${contactStartedAt}｜員工確認 ${submitted}`,submitted,status:'review',statusText:'等待主管確認已接獲聯絡',contactMethod:contactedBy,contactStartedAt,employeeConfirmedAt:submitted,supervisor,attachments:[],createdAt:record.createdAt});write(eventKey,events.slice(0,100));contactedBy='';contactStartedAt='';document.getElementById('emergencyLeaveReason').value='';document.getElementById('confirmEmergencyContact').disabled=true;document.getElementById('emergencyContactStatus').textContent='尚未發起聯絡';toast('緊急請假聯絡紀錄已送至主管後台');renderRecords()}
 function syncRecords(){const events=read(eventKey),records=read(recordKey);let changed=false;records.forEach(record=>{const event=events.find(item=>item.id===record.id);if(event&&event.status!==record.status){record.status=event.status;record.statusText=event.statusText;record.supervisorConfirmedAt=event.reviewedAt?new Date(event.reviewedAt).toLocaleString('zh-TW',{hour12:false}):now();changed=true}});if(changed){localStorage.setItem(recordKey,JSON.stringify(records));renderRecords()}}
 function renderRecords(){syncRecords.running=true;const box=document.getElementById('emergencyLeaveRecords');if(!box){syncRecords.running=false;return}const records=read(recordKey);box.innerHTML=records.length?records.map(r=>`<div class="emergency-record"><b>${r.type}・${r.statusText}</b><small>${r.id}｜${r.reason}</small><div class="emergency-timeline">✓ ${r.contactStartedAt} 發起${r.contactMethod}<br>✓ ${r.employeeConfirmedAt} 員工確認已聯絡${r.supervisorConfirmedAt?`<br>✓ ${r.supervisorConfirmedAt} 主管後台確認`: '<br>○ 等待主管後台確認'}</div></div>`).join(''):'<div class="emergency-record"><small>尚無緊急請假聯絡紀錄</small></div>';syncRecords.running=false}
 function setup(){const grid=document.querySelector('.apply-grid');if(grid&&!document.getElementById('emergencyLeaveEntry'))grid.insertAdjacentHTML('afterbegin','<button class="apply-card emergency-leave-card" id="emergencyLeaveEntry"><div class="apply-icon">☎</div><b>緊急請假</b><small>電話／LINE 聯絡當班主管</small></button>');document.getElementById('emergencyLeaveEntry')?.addEventListener('click',openEmergencyLeave);if(!document.getElementById('emergencyLeaveSubview'))document.body.insertAdjacentHTML('beforeend',`<section class="subview" id="emergencyLeaveSubview"><div class="subview-head"><button class="back-btn" id="closeEmergencyLeave">‹</button><h2>緊急請假聯絡</h2></div><div class="emergency-contact-panel"><h3>今日當班主管</h3><small>今日班別 08:45–18:00・請於上班前依企業規定完成通知</small><div class="supervisor-card"><b>${supervisor.name}・${supervisor.role}</b><small>公司電話 ${supervisor.companyPhone}</small><small>主管私人電話 ${supervisor.privatePhone}</small><small>LINE ${supervisor.line}</small></div><div class="emergency-contact-actions"><a class="call-supervisor" id="callEmergencySupervisor" href="tel:${supervisor.privatePhone.replace(/-/g,'')}">撥打主管電話</a><a class="line-supervisor" id="lineEmergencySupervisor" href="${supervisor.lineUrl}" target="_blank">開啟主管 LINE</a></div><div class="contact-status" id="emergencyContactStatus">尚未發起聯絡</div><div class="emergency-form"><label>請假類型<select id="emergencyLeaveType"><option>病假</option><option>事假</option><option>家庭照顧假</option><option>其他</option></select></label><label>簡短原因<textarea id="emergencyLeaveReason" rows="3" placeholder="請簡要說明緊急請假原因"></textarea></label></div><button class="emergency-confirm" id="confirmEmergencyContact" disabled>已聯絡主管並送出請假紀錄</button></div><h3 style="margin:18px 14px 6px">我的聯絡紀錄</h3><div id="emergencyLeaveRecords"></div></section>`);document.getElementById('closeEmergencyLeave')?.addEventListener('click',closeEmergencyLeave);document.getElementById('callEmergencySupervisor')?.addEventListener('click',()=>markContact('主管電話'));document.getElementById('lineEmergencySupervisor')?.addEventListener('click',()=>markContact('LINE'));document.getElementById('confirmEmergencyContact')?.addEventListener('click',submitEmergency);renderRecords();window.setInterval(syncRecords,1500);window.addEventListener('storage',syncRecords)}
 function addLineTools(){const actions=document.querySelector('.emergency-contact-actions');if(!actions||document.getElementById('copySupervisorLine'))return;actions.insertAdjacentHTML('beforeend',`<button type="button" id="copySupervisorLine">複製 LINE ID</button>${supervisor.lineQr?'<button type="button" id="showSupervisorQr">顯示 QR Code</button>':''}`);actions.insertAdjacentHTML('afterend',`<div class="supervisor-line-qr" id="supervisorLineQr" hidden>${supervisor.lineQr?`<img src="${supervisor.lineQr}" alt="${supervisor.name} LINE QR Code"><small>掃描後加入 ${supervisor.line}・ID ${supervisor.lineId}</small>`:''}</div>`);document.getElementById('copySupervisorLine').onclick=()=>{navigator.clipboard?.writeText(supervisor.lineId||'');markContact('LINE ID');toast(`LINE ID ${supervisor.lineId||'未設定'} 已複製`)};document.getElementById('showSupervisorQr')?.addEventListener('click',()=>{document.getElementById('supervisorLineQr').hidden=false;markContact('LINE QR Code')})}
 window.openEmergencyLeave=openEmergencyLeave;const start=()=>{setup();setTimeout(addLineTools,0)};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start();
})();
